// ── MDF AcroForm Field Reader ──
// Reads fillable PDF form fields from the MDF (010) template.
// Maps the generic field names to ParsedMDF structure.

import type { ParsedMDF } from "./ocr-engine";

// ── Field name → ParsedMDF key mapping ──
// Based on MDF (010).pdf gold standard template.
// Field names are unfortunately generic (auto-generated by the PDF editor),
// so this is a static lookup keyed to the exact form field IDs.

interface FormFieldMap {
  [fieldName: string]: {
    target: keyof ParsedMDF | "skip";
    transform?: (value: string) => string;
  };
}

// Page 2: License / Merchant Identity
// Page 3: Business / Contact
// Page 4: Bank
// Page 5: Shareholders
// Pages 6-7: Fees
// Page 9: DDM section

const FIELD_MAP: FormFieldMap = {
  // ── Merchant identity (page 2) ──
  "Merchant Trade Name 3": { target: "merchantLegalName" },
  "Merchant Trade Name 4": { target: "dba" },
  "Merchant Legal Name 2": { target: "skip" }, // Trade License number (not a ParsedMDF field)
  "Street Name 44": { target: "emirate" },
  "Street Name 3": { target: "address" },
  "Street Name 52": { target: "shopLocation" },
  "Street Name 2": { target: "poBox" },

  // ── Business details (page 3) ──
  "Street Name 7": { target: "businessType" },
  "Street Name 9": { target: "exactBusinessNature" },
  "Street Name 24": { target: "contactName" },
  "Street Name 27": { target: "contactTitle" },
  "Street Name 45": { target: "contactMobile" },
  "Street Name 47": { target: "contactWorkPhone" },
  "Street Name 29": { target: "email1" },
  "Street Name 31": { target: "email2" },
  "Street Name 43": { target: "webAddress" },
  "Street Name 46": { target: "skip" }, // "how customers reach you"

  // Phone number - also use as mobileNo
  // (In sole proprietor cases, merchant mobile = contact mobile)

  // ── Bank details (page 4) ──
  "Street Name 39": { target: "bankName" },
  "Street Name 41": { target: "iban" },
  "Street Name 38": { target: "accountTitle" },
  "Street Name 40": { target: "accountNo" },
  "Street Name 42": { target: "swiftCode" },

  // ── Annual sales → map to projectedMonthlyVolume ──
  "Street Name 16": { target: "projectedMonthlyVolume" }, // Current annual card sales
  "Street Name 18": { target: "skip" }, // Projected Y1 card sales (secondary)

  // ── DDM section (page 9) ──
  "Emirate 2": { target: "skip" },
  "IBAN No DDM 2": { target: "skip" },
  "POS/MPOS 9": { target: "numTerminals" },
};

// Fee field name patterns → card type extraction
const FEE_PATTERNS: { pattern: RegExp; cardType: string }[] = [
  { pattern: /^Debit - Visa\/Visa Electron$/i, cardType: "Visa Standard" },
  { pattern: /^Debit - Mastercard\/Maestro$/i, cardType: "Mastercard Standard" },
  { pattern: /^Debit -\s*VISA Premium$/i, cardType: "Visa Premium" },
  { pattern: /^Debit - Mastercard Premium$/i, cardType: "Mastercard Premium" },
  { pattern: /^Debit -\s*JCB$/i, cardType: "JCB" },
  { pattern: /^Debit - UnionPAY$/i, cardType: "UnionPay" },
  { pattern: /^Debit - Diners Club\/Discover$/i, cardType: "Diners/Discover" },
  { pattern: /^Debit - RUPAY$/i, cardType: "RuPay" },
  { pattern: /^Debit - Non UAE Issued Cards$/i, cardType: "International" },
  { pattern: /^Debit - Alipay$/i, cardType: "Alipay" },
  { pattern: /^Debit - WeChat PAY$/i, cardType: "WeChat Pay" },
  { pattern: /^Debit - Others$/i, cardType: "Others" },
  { pattern: /^Debit - Mercury$/i, cardType: "Mercury" },
];

// Shareholder fields (page 5 — "SHAREHOLDERS / ULTIMATE BENEFICIAL OWNER" section)
// Merchant No 81/27/61/77/79 = Authorized Signatory (NOT shareholders)
// Merchant No 115/113/129/133/137 = Shareholder 1
// Additional shareholders would follow a similar pattern
const SHAREHOLDER_FIELDS = [
  { name: "Merchant No 115", pct: "Merchant No 113", nationality: "Merchant No 129" },
  // Second shareholder row (if present in the template)
  { name: "Merchant No 82", pct: "Merchant No 114", nationality: "Merchant No 130" },
  // Third shareholder row
  { name: "Merchant No 83", pct: "Merchant No 116", nationality: "Merchant No 131" },
  // Fourth shareholder row
  { name: "Merchant No 84", pct: "Merchant No 117", nationality: "Merchant No 132" },
  // Fifth shareholder row
  { name: "Merchant No 85", pct: "Merchant No 118", nationality: "Merchant No 133" },
];

// ── Value-pattern fallback matching ──
// When FIELD_MAP doesn't cover a field, inspect the VALUE to guess what it is.

interface PDFField {
  name: string;
  value: string;
}

const UAE_EMIRATES = [
  "abu dhabi", "dubai", "sharjah", "ajman", "umm al quwain",
  "umm al-quwain", "ras al khaimah", "ras al-khaimah", "fujairah",
];

const COMPANY_INDICATORS = [
  "llc", "l.l.c", "l.l.c.", "trading", "fz-llc", "fze", "fzc",
  "est", "establishment", "company", "co.", "corp", "corporation",
  "inc", "enterprises", "group", "holdings", "limited", "ltd",
  "partners", "services", "solutions", "industries", "international",
];

function fallbackFieldMatching(fields: PDFField[], data: ParsedMDF): void {
  for (const { value } of fields) {
    if (!value) continue;

    // IBAN pattern
    if (!data.iban && /^[A-Z]{2}\d{2}[A-Z0-9]{10,30}$/.test(value.replace(/\s/g, "").toUpperCase())) {
      data.iban = value.replace(/\s/g, "").toUpperCase();
      continue;
    }

    // Email pattern
    if (!data.email1 && /\S+@\S+\.\S+/.test(value)) {
      data.email1 = value;
      continue;
    }

    // Phone pattern
    if (!data.mobileNo && /^[\d\s\+\-()]{7,15}$/.test(value.trim())) {
      data.mobileNo = value.trim();
      continue;
    }

    // UAE Emirate
    if (!data.emirate && UAE_EMIRATES.some((e) => value.toLowerCase().includes(e))) {
      data.emirate = value.trim();
      continue;
    }

    // Company name (contains LLC, Trading, etc.)
    const valueLower = value.toLowerCase();
    if (COMPANY_INDICATORS.some((ind) => valueLower.includes(ind.toLowerCase()))) {
      if (!data.merchantLegalName) {
        data.merchantLegalName = value.trim();
      } else if (!data.dba) {
        data.dba = value.trim();
      }
    }
  }
}

/**
 * Extract ParsedMDF from a PDF with AcroForm fields (fillable PDF).
 * Returns null if the PDF has no form fields or isn't the expected template.
 */
export async function extractMDFFormFields(arrayBuffer: ArrayBuffer): Promise<ParsedMDF | null> {
  try {
    const { PDFDocument, PDFTextField, PDFDropdown, PDFCheckBox } = await import("pdf-lib");
    const pdf = await PDFDocument.load(arrayBuffer, { ignoreEncryption: true });
    const form = pdf.getForm();
    const fields = form.getFields();

    if (fields.length < 20) return null; // Not a fillable MDF

    // Read all text field values
    const values = new Map<string, string>();
    let filledCount = 0;

    for (const field of fields) {
      const name = field.getName();
      try {
        let value = "";
        if (field instanceof PDFTextField) {
          value = field.getText() || "";
        } else if (field instanceof PDFDropdown) {
          const selected = field.getSelected();
          value = Array.isArray(selected) ? selected.join(", ") : (selected || "");
        } else if (field instanceof PDFCheckBox) {
          value = field.isChecked() ? "CHECKED" : "";
        }
        if (value.trim()) {
          values.set(name, value.trim());
          filledCount++;
        }
      } catch {
        // Skip unreadable fields
      }
    }

    if (filledCount < 3) return null; // Not enough filled fields

    // Build ParsedMDF from form field values
    const data: ParsedMDF = {
      rawText: "",
      feeSchedule: [],
      terminalFees: [],
      shareholders: [],
      keySuppliers: [],
      keyCustomers: [],
      sanctionsExposure: [],
      productPOS: false,
      productECOM: false,
      productMPOS: false,
      productMOTO: false,
      hasOtherAcquirer: false,
    };

    // Map simple fields
    for (const [fieldName, value] of values) {
      const mapping = FIELD_MAP[fieldName];
      if (mapping && mapping.target !== "skip") {
        const key = mapping.target as keyof ParsedMDF;
        const transformed = mapping.transform ? mapping.transform(value) : value;
        // Only set string fields, skip arrays/booleans
        if (typeof (data as any)[key] === "undefined" || typeof (data as any)[key] === "string") {
          // Don't overwrite if already set with a non-empty value
          if (!(data as any)[key] || (data as any)[key] === "") {
            (data as any)[key] = transformed;
          }
        }
      }
    }

    // Value-pattern fallback: scan field values for IBAN, email, phone, emirate, company names
    const allFields: PDFField[] = [];
    for (const [name, value] of values) {
      allFields.push({ name, value });
    }
    fallbackFieldMatching(allFields, data);

    // mobileNo — use contactMobile if mobileNo not set separately
    if (!data.mobileNo && data.contactMobile) {
      data.mobileNo = data.contactMobile;
    }

    // Fee schedule from Debit fields (POS rates)
    for (const fp of FEE_PATTERNS) {
      for (const [name, value] of values) {
        if (fp.pattern.test(name)) {
          const rate = value.replace(/[^0-9.]/g, "");
          if (rate) {
            // Look for corresponding ecom rate (suffix "3" = manual/ecom processing)
            const ecomName = name + " 3";
            const ecomValue = values.get(ecomName)?.replace(/[^0-9.]/g, "") || undefined;
            data.feeSchedule.push({
              cardType: fp.cardType,
              posRate: rate,
              ecomRate: ecomValue,
            });
          }
          break;
        }
      }
    }

    // Terminal fees
    const oneTimeFee = values.get("One Time Fee 3");
    if (oneTimeFee) {
      data.terminalFees.push({ category: "pos", label: "One-off Fee", amount: oneTimeFee });
    }
    const annualRent = values.get("Annual Rent 3");
    if (annualRent) {
      data.terminalFees.push({ category: "pos", label: "Annual Rent", amount: annualRent });
    }

    // Shareholders
    for (const sh of SHAREHOLDER_FIELDS) {
      const name = values.get(sh.name);
      if (name) {
        data.shareholders.push({
          name,
          sharesPercentage: values.get(sh.pct),
          nationality: values.get(sh.nationality),
        });
      }
    }

    // POS product detection
    const posCount = values.get("POS/MPOS 9");
    if (posCount && parseInt(posCount) > 0) {
      data.productPOS = true;
    }
    const ecomField = values.get("Online 5");
    if (ecomField && /yes/i.test(ecomField)) {
      data.productECOM = true;
    }

    // Build rawText from all form values for template matching
    const textParts: string[] = [];
    for (const [name, value] of values) {
      textParts.push(`${name}: ${value}`);
    }
    // Also include the text layer for context
    data.rawText = textParts.join("\n");

    return data;
  } catch (err) {
    console.warn("[mdf-form-reader] AcroForm extraction failed:", err);
    return null;
  }
}

/**
 * Check if a PDF is a fillable form (has AcroForm fields).
 */
export async function isFillablePDF(arrayBuffer: ArrayBuffer): Promise<boolean> {
  try {
    const { PDFDocument } = await import("pdf-lib");
    const pdf = await PDFDocument.load(arrayBuffer, { ignoreEncryption: true });
    const form = pdf.getForm();
    return form.getFields().length > 20;
  } catch {
    return false;
  }
}
